const All = [
  {
    id: 1,
    Image: require("../assets/productImage/movie/ajmer.jpg"),
    userImage: require("../assets/images/men1.jpg"),
    price: "276",
    userName: "Ashok Kumar",
    title: "Ajmer 92",
    geners: "Drama",
    imdb: " 8.9/10",
    language: "Hindi (CAM)",
    description:
      "A heart-wrenching story of 250 girls from Ajmer. Ajmer 92 releasing in cinemas on 14th July.",
  },
  {
    id: 2,
    userName: "Rishab Kumar",
    title: "MY NEWBORN",
    userImage: require("../assets/images/men2.jpg"),
    price: "230",
    Image: require("../assets/productImage/baby/baby2.jpg"),
    description:
      "MY NEWBORN by 10CLUB Fastdry Bibs - 6pcs | Baby bibs for 6 to 12 months | Bibs for new born baby 0 to 6 months | Waterproof Spill Resistant Bibs | Soft cotton bib | Infant Apron",
  },
  {
    id: 3,
    userName: "Rahul Rai",
    title: "CUTE LANDINGS Baby's",
    userImage: require("../assets/images/men3.jpg"),
    price: "240",
    Image: require("../assets/productImage/baby/baby3.jpg"),
    description:
      "CUTE LANDINGS Baby's New Born Baby Hosiery Cotton Jhabla/T Shirts With Nappies/Langot And Caps/Infant Clothes/Combo/Gift Set/Dress/Essentials/All Products/Regular Wear (Pack Of 4) (0-3 Months)",
  },
  {
    id: 4,
    title: "Practical Modern JavaScript",
    userName: "Rastogi Rai",
    title: "Dive into ES6 and the Future of JavaScript",
    Image: require("../assets/productImage/books/book9.jpg"),
    author: "Nicolás Bevacqua",
    published: "2017-07-16T00:00:00.000Z",
    publisher: "O'Reilly Media",
    pages: 334,
    userImage: require("../assets/images/men4.jpg"),
    price: "254",
    description:
      "To get the most out of modern JavaScript, you need learn the latest features of its parent specification, ECMAScript 6 (ES6). This book provides a highly practical look at ES6, without getting lost in the specification or its implementation details.",
    website: "https://github.com/mjavascript/practical-modern-javascript",
  },
  {
    id: 5,
    userName: "Birendra Kumar",
    title: "Cable World",
    userImage: require("../assets/images/men5.jpg"),
    price: "188",
    Image: require("../assets/productImage/baby/baby5.jpg"),
    description:
      "Cable World® Colourful Plastic Non Toxic Set of 7 Attractive Rattles and Teathers for New Borns, Baby,Kid (Multi Color)",
  },
  {
    id: 6,
    userName: "Subhansu Kumar",
    title: "Kwitchy",
    userImage: require("../assets/images/men6.jpg"),
    price: "999",
    Image: require("../assets/productImage/baby/baby6.jpg"),
    description:
      "Kwitchy 12 in 1 New Born Baby Gift Pack | Combo Set | New Born Baby Items| New Born Baby Products All (0-6 Months) (12 in 1)",
  },
  {
    id: 7,
    userName: "Rahul Raj",
    title: "Baby Grooming Kit",
    userImage: require("../assets/images/men7.jpg"),
    price: "394",
    Image: require("../assets/productImage/baby/baby7.jpg"),
    description:
      "LuvLap 7In1 Baby Grooming Kit,Portable Baby Grooming Kit for New Born Baby,Finger Brush,Hair Brush,Comb,Baby Nail Scissor,Baby Nail Cutter,Tweezer,Nail Filer,Newborn,Infants,Toddlers (White), 1 Count",
  },
  {
    id: 8,
    userName: "Brijesh Kumar",
    title: "Speaking JavaScript",
    title: "An In-Depth Guide for Programmers",
    Image: require("../assets/productImage/books/book8.jpg"),
    author: "Axel Rauschmayer",
    published: "2014-04-08T00:00:00.000Z",
    publisher: "O'Reilly Media",
    pages: 460,
    userImage: require("../assets/images/men8.jpg"),
    price: "128",
    description:
      "Like it or not, JavaScript is everywhere these days -from browser to server to mobile- and now you, too, need to learn the language or dive deeper than you have. This concise book guides you into and through JavaScript, written by a veteran programmer who once found himself in the same position.",
    website: "http://speakingjs.com/",
  },
  {
    id: 9,
    userName: "Rai Bahadur",
    title: "Rethinking Productivity in Software Engineering",
    title: "",
    Image: require("../assets/productImage/books/book3.jpg"),
    author: "Caitlin Sadowski, Thomas Zimmermann",
    published: "2019-05-11T00:00:00.000Z",
    publisher: "Apress",
    pages: 310,
    userImage: require("../assets/images/men9.jpg"),
    price: "567",
    description:
      'Get the most out of this foundational reference and improve the productivity of your software teams. This open access book collects the wisdom of the 2017 "Dagstuhl" seminar on productivity in software engineering, a meeting of community leaders, who came together with the goal of rethinking traditional definitions and measures of productivity.',
    website: "https://doi.org/10.1007/978-1-4842-4221-6",
  },
  {
    id: 10,
    userName: "Piyush Kumar",
    title: "Cotton Mittens&Booties",
    userImage: require("../assets/images/men10.jpg"),
    price: "460",
    Image: require("../assets/productImage/baby/baby9.jpg"),
    description:
      "MOM'S DARLING Cotton Mittens&Booties For New Born Baby (0-6 Months)-Pack Of 4 Pairs|Cotton Gloves With Gentle Elastic Wristbands&Booties For Baby 0 To 6 Months|New Born Baby Products.,Multicolor",
  },
  {
    id: 11,
    userName: "Abhishek Kumar",
    title: "Baby Washcloth",
    userImage: require("../assets/images/men11.jpg"),
    price: "212",
    Image: require("../assets/productImage/baby/baby10.jpg"),
    description:
      "LuvLap Hosiery Cotton Cloth Premium Baby Washcloth for New Born, Washable, Reusable, Absorbent, Extra Soft Face Towels/Washcloth for Babies, Starfish Print, Pack of 7 Pcs, Multicolour",
  },
  {
    id: 12,
    userName: "Prince Aditiya",
    title: "Eloquent JavaScript, Third Edition",
    title: "A Modern Introduction to Programming",
    Image: require("../assets/productImage/books/book10.jpg"),
    author: "Marijn Haverbeke",
    published: "2018-12-04T00:00:00.000Z",
    publisher: "No Starch Press",
    pages: 472,
    userImage: require("../assets/images/men12.jpg"),
    price: "345",
    description:
      "JavaScript lies at the heart of almost every modern web application, from social apps like Twitter to browser-based game frameworks like Phaser and Babylon. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications.",
    website: "http://eloquentjavascript.net/",
  },
  {
    id: 13,
    userName: "Ricky Kumar",
    title: "First Kick Baby Blankets",
    userImage: require("../assets/images/men13.jpg"),
    price: "498",
    Image: require("../assets/productImage/baby/baby4.jpg"),
    description:
      "First Kick Baby Blankets New Born Combo Pack of Hooded Wrapper Sleeping Bag and Baby Bath Towel for 0-6 Months Baby Boys and Baby Girls,Pink, Pack of 2",
  },
  {
    id: 14,
    userName: "Subham Kumar",
    title: "Understanding ECMAScript 6",
    title: "The Definitive Guide for JavaScript Developers",
    Image: require("../assets/productImage/books/book8.jpg"),
    author: "Nicholas C. Zakas",
    published: "2016-09-03T00:00:00.000Z",
    publisher: "No Starch Press",
    pages: 352,
    userImage: require("../assets/images/men14.jpg"),
    price: "435",
    description:
      "ECMAScript 6 represents the biggest update to the core of JavaScript in the history of the language. In Understanding ECMAScript 6, expert developer Nicholas C. Zakas provides a complete guide to the object types, syntax, and other exciting changes that ECMAScript 6 brings to JavaScript.",
    website: "https://leanpub.com/understandinges6/read",
  },
  {
    id: 15,
    userName: "Subodh Raj",
    title: "Learning JavaScript Design Patterns",
    title: "A JavaScript and jQuery Developer's Guide",
    Image: require("../assets/productImage/books/book6.jpg"),
    author: "Addy Osmani",
    published: "2012-08-30T00:00:00.000Z",
    publisher: "O'Reilly Media",
    pages: 254,
    userImage: require("../assets/images/men15.jpg"),
    price: "483",
    description:
      "With Learning JavaScript Design Patterns, you'll learn how to write beautiful, structured, and maintainable JavaScript by applying classical and modern design patterns to the language. If you want to keep your code efficient, more manageable, and up-to-date with the latest best practices, this book is for you.",
    website:
      "http://www.addyosmani.com/resources/essentialjsdesignpatterns/book/",
  },
  {
    id: 16,
    userName: "Ram Benarji",
    title: "You Don't Know JS Yet",
    title: "Get Started",
    Image: require("../assets/productImage/books/book5.jpg"),
    author: "Kyle Simpson",
    published: "2020-01-28T00:00:00.000Z",
    publisher: "Independently published",
    pages: 143,
    userImage: require("../assets/images/men16.jpg"),
    price: "298",
    description:
      "The worldwide best selling You Don't Know JS book series is back for a 2nd edition: You Don't Know JS Yet. All 6 books are brand new, rewritten to cover all sides of JS for 2020 and beyond.",
    website:
      "https://github.com/getify/You-Dont-Know-JS/tree/2nd-ed/get-started",
  },
  {
    id: 17,
    userName: "Vicky Kumar",
    title: "Pro Git",
    title: "Everything you neeed to know about Git",
    Image: require("../assets/productImage/books/book4.jpg"),
    author: "Scott Chacon and Ben Straub",
    published: "2014-11-18T00:00:00.000Z",
    publisher: "Apress; 2nd edition",
    pages: 458,
    userImage: require("../assets/images/men17.jpg"),
    price: "987",
    description:
      "Pro Git (Second Edition) is your fully-updated guide to Git and its usage in the modern world. Git has come a long way since it was first developed by Linus Torvalds for Linux kernel development. It has taken the open source world by storm since its inception in 2005, and this book teaches you how to use it like a pro.",
    website: "https://git-scm.com/book/en/v2",
  },
  {
    id: 18,
    Image: require("../assets/productImage/movie/afwah.jpg"),
    userImage: require("../assets/images/men18.jpg"),
    price: "342",
    userName: "Pandit Rai Kumar",
    title: "Afwaah",
    geners: "Drama, Thriller",
    imdb: "4.9/10",
    language: "Hindi(ORG 5.1)",
    description:
      "An advertising professional and a political heiress whose lives are upended by a viral social media rumour.",
  },
  {
    id: 19,
    userName: "Raju Raj",
    title: "Learning JavaScript Design Patterns",
    title: "A JavaScript and jQuery Developer's Guide",
    Image: require("../assets/productImage/books/book2.jpg"),
    author: "Addy Osmani",
    published: "2012-08-30T00:00:00.000Z",
    publisher: "O'Reilly Media",
    pages: 254,
    userImage: require("../assets/images/men19.jpg"),
    price: "678",
    description:
      "With Learning JavaScript Design Patterns, you'll learn how to write beautiful, structured, and maintainable JavaScript by applying classical and modern design patterns to the language. If you want to keep your code efficient, more manageable, and up-to-date with the latest best practices, this book is for you.",
    website:
      "http://www.addyosmani.com/resources/essentialjsdesignpatterns/book/",
  },
  {
    id: 20,
    title: "You Don't Know JS Yet",
    userName: "Kishan Kumar",
    title: "Get Started",
    Image: require("../assets/productImage/books/book1.jpg"),
    author: "Kyle Simpson",
    published: "2020-01-28T00:00:00.000Z",
    publisher: "Independently published",
    pages: 143,
    userImage: require("../assets/images/men20.jpg"),
    price: "432",
    description:
      "The worldwide best selling You Don't Know JS book series is back for a 2nd edition: You Don't Know JS Yet. All 6 books are brand new, rewritten to cover all sides of JS for 2020 and beyond.",
    website:
      "https://github.com/getify/You-Dont-Know-JS/tree/2nd-ed/get-started",
  },
  {
    id: 21,
    userName: "Karan Raj",
    title: "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
    userImage: require("../assets/images/men1.jpg"),
    price: "109.95",
    description:
      "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
    category: "men's clothing",
    Image: require("../assets/productImage/electronics/e1.jpg"),
    rating: {
      rate: 3.9,
      count: 120,
    },
  },
  {
    id: 22,
    userName: "Arjun Reddy",
    title: "WD 2TB Elements Portable External Hard Drive - USB 3.0 ",
    userImage: require("../assets/images/men2.jpg"),
    price: "64",
    description:
      "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system",
    category: "electronics",
    Image: require("../assets/productImage/electronics/e2.jpg"),
    rating: {
      rate: 3.3,
      count: 203,
    },
  },
  {
    id: 23,
    userName: "Keshav Kumar",
    title: "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
    userImage: require("../assets/images/men3.jpg"),
    price: "109",
    description:
      "Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)",
    category: "electronics",
    Image: require("../assets/productImage/electronics/e3.jpg"),
    rating: {
      rate: 2.9,
      count: 470,
    },
  },
  {
    id: 24,
    userName: "Ratan Rai",
    title:
      "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
    userImage: require("../assets/images/men4.jpg"),
    price: "109",
    description:
      "3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
    category: "electronics",
    Image: require("../assets/productImage/electronics/e4.jpg"),
    rating: {
      rate: 4.8,
      count: 319,
    },
  },
  {
    id: 25,
    userName: "Santosh Kumar",
    title:
      "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive",
    userImage: require("../assets/images/men5.jpg"),
    price: "114",
    description:
      "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
    category: "electronics",
    Image: require("../assets/productImage/electronics/e5.jpg"),
    rating: {
      rate: 4.8,
      count: 400,
    },
  },
  {
    id: 26,
    userName: "Sanjay Mishra",
    title: "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin",
    userImage: require("../assets/images/men6.jpg"),
    price: "599",
    description:
      "21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz",
    category: "electronics",
    Image: require("../assets/productImage/electronics/e6.jpg"),
    rating: {
      rate: 2.9,
      count: 250,
    },
  },
  {
    id: 27,
    Image: require("../assets/productImage/movie/bholla.jpg"),
    userImage: require("../assets/images/men7.jpg"),
    price: "542",
    userName: "Rai Bahadur",
    title: "Bholaa Shankar",
    geners: "Action, Drama",
    imdb: "3.2/10",
    language: "Hindi (ORG 5.1)",
    description:
      "A doting brother tries to hunt down notorious criminals who had harmed his sister.",
  },
  {
    id: 28,
    userName: "Ravi Kishan",
    title:
      "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
    userImage: require("../assets/images/men8.jpg"),
    price: "209",
    description:
      "3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
    category: "electronics",
    Image: require("../assets/productImage/electronics/e3.jpg"),
    rating: {
      rate: 4.8,
      count: 319,
    },
  },
  {
    id: 29,
    Image: require("../assets/productImage/movie/bambai.jpg"),
    userImage: require("../assets/images/men9.jpg"),
    price: "435",
    userName: "Ritu Raj",
    title: "Bambai Meri Jaan",
    geners: "Crime, Drama",
    imdb: "N/A/10",
    language: "Hindi (ORG 2.0)",
    description:
      "A sneak into the post-independence Bombay and streets riddled with crime. An honest cop’s journey as he tries to protect his family.",
  },
  {
    id: 30,
    Image: require("../assets/productImage/movie/balupu.jpg"),
    userImage: require("../assets/images/men10.jpg"),
    price: "234",
    userName: "Raja Kumar",
    title: "Balupu",
    geners: "Action, Comedy",
    imdb: "6.1/10",
    language: "Hindi (ORG 2.0)",
    description:
      "Ravi (Ravi Teja) works as a collection agent of ICICI in Bangalore and leads a happy life along with his friends and his father Mohan Rao (Prakash Raj) who wishes to see Ravi married to a girl soon. Once Ravi rushes to a Hospital where his friend (‘Satyam’ Rajesh) is admitted as he tried to commit suicide by drinking nail polish solution and asks the reason for it. Then he describes about the traits of Shruti (Shruti Haasan) and her uncle Crazy Mohan (Brahmanandam). The duo have a habit of cheating gullible young men including his friend and Ravi decides to teach them a lesson.",
  },
  {
    id: 31,
    Image: require("../assets/productImage/movie/breaking.jpg"),
    userImage: require("../assets/images/men11.jpg"),
    price: "765",
    userName: "Akhilesh Kumar",
    title: "Breaking",
    geners: "Crime, Drama, Thriller",
    imdb: "6.8/10",
    language: "Hindi (ORG 2.0)",
    description:
      "A Marine war veteran faces mental and emotional challenges when he tries to reintegrate back into civilian life.",
  },
  {
    id: 32,
    userImage: require("../assets/images/men12.jpg"),
    price: "546",
    userName: "Anubhav Kumar",
    title: " Baby bather for baby",
    price: "799",
    Image: require("../assets/productImage/baby/baby8.jpg"),
    description:
      "LuvLap Jungle Tales baby bather for baby 0 - 6 months, New Born Baby Bath Chair, 3 position adjustable, Washable soft Mesh, Large Seat (Multicolor)",
  },
  {
    id: 33,
    Image: require("../assets/productImage/movie/barbie.jpg"),
    userImage: require("../assets/images/men13.jpg"),
    price: "453",
    userName: "Visheswar Kumar",
    title: "Barbie",
    geners: "Adventure, Comedy, Fantasy",
    imdb: "7.4/10",
    language: "English (ORG)",
    description:
      "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
  },
  {
    id: 34,
    Image: require("../assets/productImage/movie/campus.jpg"),
    userImage: require("../assets/images/men14.jpg"),
    price: "234",
    userName: "Deep Rai",
    title: "Campus Beats",
    geners: "Drama",
    imdb: "10.0/10",
    language: "Hindi (ORG 2.0)",
    description:
      "What starts as an agenda to get closure for her past , a GenZ girl uncovers her hidden dancing talent and in the process experiences the real meaning of friendship, love, freedom and justice in a modern dance academy divided sharply across socio-economic class.",
  },
  {
    id: 35,
    userName: "Deepu Kumar",
    title:
      "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ",
    userImage: require("../assets/images/men15.jpg"),
    price: "999.99",
    description:
      "49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag",
    category: "electronics",
    Image: require("../assets/productImage/electronics/e7.jpg"),
    rating: {
      rate: 2.2,
      count: 140,
    },
  },
  {
    id: 36,
    userName: "Harish Kumar",
    title: "Baby Blankets",
    userImage: require("../assets/images/men16.jpg"),
    price: "269",
    Image: require("../assets/productImage/baby/baby1.jpg"),
    description:
      "OYO BABY Baby Blankets New Born Babies | Pack of 1, Super Soft Baby Wrapper Baby Sleeping Bag for Baby Boys, Baby Girls, Babies (76cm x 70cm, 0-6 Months, Fleece, Skin Friendly, Star Grey)",
  },
  {
    id: 37,
    Image: require("../assets/productImage/movie/best.jpg"),
    userImage: require("../assets/images/men17.jpg"),
    price: "342",
    userName: "Harsh Vardhan",
    title: "The Best Man",
    geners: "Action, Thriller",
    imdb: "4.1/10",
    language: "English (ORG)",
    description:
      "Mercenaries seize control of a remote resort hotel during a wedding and it’s up to the best man, the groom and their drunken best friend to stop the terrorists and save the hostages.",
  },
  {
    id: 38,
    Image: require("../assets/productImage/movie/charli.jpg"),
    userImage: require("../assets/images/men18.jpg"),
    price: "827",
    userName: "Krishna Kumar",
    title: "Charlie Chopra & The Mystery of Solang Valley",
    geners: "Mystery",
    imdb: "7.5/10",
    language: "Hindi (ORG 2.0)",
    description:
      "A rich man dead, a town full of suspects, narratives filled with lies and an innocent convict. How will Charlie navigate through the mystery when every face hides a secret?",
  },
];

export default All;
