const Movie = [
  {
    id: 1,
    Image: require("../assets/productImage/movie/bambai.jpg"),
    userImage: require("../assets/images/men1.jpg"),
    price: "876",
    userName: "Rahul Kumar",
    title: "Bambai Meri Jaan",
    geners: "Crime, Drama",
    imdb: "N/A/10",
    language: "Hindi (ORG 2.0)",
    description:
      "A sneak into the post-independence Bombay and streets riddled with crime. An honest cop’s journey as he tries to protect his family.",
  },
  {
    id: 2,
    Image: require("../assets/productImage/movie/balupu.jpg"),
    userImage: require("../assets/images/men1.jpg"),
    price: "654",
    userName: "Vikash kumar",
    title: "Balupu",
    geners: "Action, Comedy",
    imdb: "6.1/10",
    language: "Hindi (ORG 2.0)",
    description:
      "Ravi (Ravi Teja) works as a collection agent of ICICI in Bangalore and leads a happy life along with his friends and his father Mohan Rao (Prakash Raj) who wishes to see Ravi married to a girl soon. Once Ravi rushes to a Hospital where his friend (‘Satyam’ Rajesh) is admitted as he tried to commit suicide by drinking nail polish solution and asks the reason for it. Then he describes about the traits of Shruti (Shruti Haasan) and her uncle Crazy Mohan (Brahmanandam). The duo have a habit of cheating gullible young men including his friend and Ravi decides to teach them a lesson.",
  },
  {
    id: 3,
    Image: require("../assets/productImage/movie/breaking.jpg"),
    userImage: require("../assets/images/men1.jpg"),
    price: "265",
    userName: "Bhupesh Kumar",
    title: "Breaking",
    geners: "Crime, Drama, Thriller",
    imdb: "6.8/10",
    language: "Hindi (ORG 2.0)",
    description:
      "A Marine war veteran faces mental and emotional challenges when he tries to reintegrate back into civilian life.",
  },
  {
    id: 4,
    Image: require("../assets/productImage/movie/barbie.jpg"),
    userImage: require("../assets/images/men1.jpg"),
    price: "654",
    userName: "Rishab Kumar",
    title: "Barbie",
    geners: "Adventure, Comedy, Fantasy",
    imdb: "7.4/10",
    language: "English (ORG)",
    description:
      "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
  },
  {
    id: 5,
    Image: require("../assets/productImage/movie/afwah.jpg"),
    userImage: require("../assets/images/men1.jpg"),
    price: "453",
    userName: "Ritu Raj",
    title: "Afwaah",
    geners: "Drama, Thriller",
    imdb: "4.9/10",
    language: "Hindi(ORG 5.1)",
    description:
      "An advertising professional and a political heiress whose lives are upended by a viral social media rumour.",
  },
  {
    id: 6,
    Image: require("../assets/productImage/movie/campus.jpg"),
    userImage: require("../assets/images/men1.jpg"),
    price: "345",
    userName: "Piyush Kumar",
    title: "Campus Beats",
    geners: "Drama",
    imdb: "10.0/10",
    language: "Hindi (ORG 2.0)",
    description:
      "What starts as an agenda to get closure for her past , a GenZ girl uncovers her hidden dancing talent and in the process experiences the real meaning of friendship, love, freedom and justice in a modern dance academy divided sharply across socio-economic class.",
  },
  {
    id: 7,
    Image: require("../assets/productImage/movie/ajmer.jpg"),
    userImage: require("../assets/images/men1.jpg"),
    price: "765",
    userName: "Subham Kumar",
    title: "Ajmer 92",
    geners: "Drama",
    imdb: " 8.9/10",
    language: "Hindi (CAM)",
    description:
      "A heart-wrenching description of 250 girls from Ajmer. Ajmer 92 releasing in cinemas on 14th July.",
  },
  {
    id: 8,
    Image: require("../assets/productImage/movie/best.jpg"),
    userImage: require("../assets/images/men1.jpg"),
    price: "354",
    userName: "Prince Aditya",
    title: "The Best Man",
    geners: "Action, Thriller",
    imdb: "4.1/10",
    language: "English (ORG)",
    description:
      "Mercenaries seize control of a remote resort hotel during a wedding and it’s up to the best man, the groom and their drunken best friend to stop the terrorists and save the hostages.",
  },
  {
    id: 9,
    Image: require("../assets/productImage/movie/charli.jpg"),
    userImage: require("../assets/images/men1.jpg"),
    price: "276",
    userName: "Saurabh Kumar",
    title: "Charlie Chopra & The Mystery of Solang Valley",
    geners: "Mystery",
    imdb: "7.5/10",
    language: "Hindi (ORG 2.0)",
    description:
      "A rich man dead, a town full of suspects, narratives filled with lies and an innocent convict. How will Charlie navigate through the mystery when every face hides a secret?",
  },
  {
    id: 10,
    Image: require("../assets/productImage/movie/bholla.jpg"),
    userImage: require("../assets/images/men1.jpg"),
    price: "",
    userName: "Vicky Ghosh",
    title: "Bholaa Shankar",
    geners: "Action, Drama",
    imdb: "3.2/10",
    language: "Hindi (ORG 5.1)",
    description:
      "A doting brother tries to hunt down notorious criminals who had harmed his sister.",
  },
];

export default Movie;
