const Data = [
  {
    id: "1",
    title: "Aadmiyon ka Pyar",
    thumbnailUrl: require("../assets/images/img3.png"),
    views: "24,969,123",
    author: "Rohan Kumar",
    video: require("../assets/video/vid1.mp4"),
  },
  {
    id: "2",
    title: "Best Lines",
    thumbnailUrl: require("../assets/images/img4.png"),
    views: "969,123",
    author: "Rishab Pratap Singh",
    video: require("../assets/video/vid2.mp4"),
  },
  {
    id: "3",
    title: "Motivational Lines",
    thumbnailUrl: require("../assets/images/img5.png"),
    views: "24,969",
    author: "Roshan Pratap",
    video: require("../assets/video/vid3.mp4"),
  },
  {
    id: "4",
    title: "Best Lines",
    thumbnailUrl: require("../assets/images/img6.png"),
    views: "24,123",
    author: "Subham Raj",
    video: require("../assets/video/vid4.mp4"),
  },
  {
    id: "5",
    title: "Motivational Lines",
    thumbnailUrl: require("../assets/images/img8.png"),
    views: "2369,123",
    author: "Prince Kumar",
    video: require("../assets/video/vid5.mp4"),
  },
  {
    id: "6",
    title: "Motivational Speaker",
    thumbnailUrl: require("../assets/images/img13.png"),
    views: "24,923",
    author: "Prince Kumar",
    video: require("../assets/video/vid6.mp4"),
  },
  {
    id: "7",
    title: "Daily Fitness",
    thumbnailUrl: require("../assets/images/img7.png"),
    views: "269,123",
    author: "Sam Bahadur",
    video: require("../assets/video/vid7.mp4"),
  },
  {
    id: "8",
    title: "Motivational Touch",
    thumbnailUrl: require("../assets/images/img14.png"),
    views: "24,956",
    author: "Prince Kumar",
    video: require("../assets/video/vid8.mp4"),
  },
  {
    id: "9",
    title: "Four reality you must know",
    thumbnailUrl: require("../assets/images/img9.png"),
    views: "24,967",
    author: "Soukat Kumar",
    video: require("../assets/video/vid9.mp4"),
  },
  {
    id: "10",
    title: "Comedy",
    thumbnailUrl: require("../assets/images/img10.png"),
    views: "23,465,23",
    author: "Rishab Kumar",
    video: require("../assets/video/vid10.mp4"),
  },
  {
    id: "11",
    title: "Best Speaker",
    thumbnailUrl: require("../assets/images/img11.png"),
    views: "14,323",
    author: "Ritu Chauhan",
    video: require("../assets/video/vid11.mp4"),
  },
  {
    id: "12",
    title: "Best Comedy",
    thumbnailUrl: require("../assets/images/img12.png"),
    views: "876,123",
    author: "Bhupesh Kumar",
    video: require("../assets/video/vid12.mp4"),
  },
];

export default Data;
